project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Blog.qmd
        text: Personal Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

editor: visual

resources:
  - photos/japan/*.mp4
  - photos/japan/*.MOV


