project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:  # Dropdown for multiple project pages
          - text: 'Euro Cycle 2024'
            href: euro_cycle.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

editor: visual


