---
output:
  html_document:
    theme: yeti
    highlight: tango
---
***

### SUMMARY 

Professionally, I spend my time collecting, analyzing, modeling, and visualizing data related to *urban planning*, *transportation*, *public policy*, *sustainability*, and *environmental science*. For much of this work I use the [R programming language](https://www.r-project.org/about.html). I am currently employed at the Tahoe Regional Planning Agency as a Data Modeler/Analyst. 

***

### SKILLS 
* Data analysis, data collection, and visualization: R, Python, Tableau, SQL, Microsoft Access, Microsoft Excel 
* Geospatial analysis & mapping: R, ArcGIS, QGIS, Tableau  
* Writing and publication: RMarkdown, Adobe InDesign, Microsoft Word, LaTeX
* Web Design: Rmarkdown
* Foreign Language: Spanish (intermediate) 

***

### EDUCATION 

* University of Washington - Master's of Urban Planning (2014)
* Western Washington University - B.A. Environmental Studies (2010)

***

### WORK EXPERIENCE 

* Data Modeler/Analyst, Tahoe Regional Planning Agency, (July 2017 - Present) 
* Assistant Planner, Puget Sound Regional Council,  (October 2014-June 2017) 
* Outreach & Data Analyst, Seattle City Light, (July 2013 - April, 2014) 
* Communication Specialist, University of Washington, (Sept. 2012-June 2013) 
* Assistant, Solar Energy International (SEI), (2011) . Green the Capitol Intern, United States House of Representatives, (2010) 

***

### RESEARCH 
* Master's Thesis: Assessing the relationship between city growth and electricity use over time: A comparative analysis of Chandigarh and Seattle (University of Washington, 2014) 
* Public Street and Area Lighting Inventory Phase 1: Survey Results, Municipal Solid-State Street Lighting Consortium (Seattle City Light, 2014)

***

### VOLUNTEER
* Commissioner, City of Seattle Urban Forestry Commission (Seattle, WA, 2016-2017)
* Founder, Friends of North Lake Union - FONLU (Seattle, WA, 2015-2017) 
* Seattle Audobon Society - Puget Sound Seabird Study (Seattle, WA, 2015-2017) . Board Member, Wallingford Community Council (Seattle, WA, 2015-2016)

***

### AWARDS
* 1st Place Winner, 2010 AWMA Environmental Challenge International (Eci) (Calgary, Canada, 2010) 
* 1st Place Winner, 2009 PNWIS/AWMA Environmental Challenge, (Cle Elum, Washington, 2009)

***

### PROJECTS 
* Chandigarh Urban Lab: Solar Spine Site Plan (University of Washington, 2014) 
* City of Buckley Site Master Plan (University of Washington, 2013)
* Monkey Point Wind Turbine Maintenance, (Solar Energy International, 2011) 
* Mujeres Solares de Totogalpa Solar Installation, (Solar Energy International, 2011) 
* Haiti Post-Earthquake Planning, (Western Washington University, 2010) 
* Yew Street Urbanization Environmental Impact Assessment (Western Washington University, 2010) 
* Downtown Bellingham Revitalization Plan, (Western Washington University, 2010)

***

### CONTINUED EDUCATION
* Solar Energy International: Records of Completion (RoC) 
* PV 101: Solar Electric Design and Installation (online) 
* PV 206: Solar Business & Technical Sales (online)
* PV 203: Solar Electric Battery Based Design & Installation (Guemes Island, WA, 2011) - RD 206: Sustainable Community Development: Wind Power for Rural Communities (Bluefields, Nicaragua, 2011)
* RD 205: Sustainable Community Development: Renewable Energy for Rural Communities (Totogalpa, Nicaragua, 2011)
* RD 101: Renewable Energy for the Developing World (online) 
* American Institute for Avalanche Research and Education (AIARE): AIARE I Certification (Pro Guiding Service, 2016)

***

### INTERNATIONAL EXPERIENCE
* Chandigarh Urban Lab (Chandigarh, India, 2014): Graduate research on urbanization, sustainable development, and historic preservation
* Sustainable Community Development (Nicaragua, 2011): Community development focused on renewable energy in rural communities 
* International Study Abroad (ISA) (Heredia, Costa Rica, 2008): Immersive undergraduate program in environmental studies and spanish language