---
title: ""
output:
  html_document:
    highlight: tango
---

***

### *2019*

* Activity-Based Travel Demand Model - TBD

***

### *2018*

* [Travel Behavior Survey](http://www.trpa.org/wp-content/uploads/travel_survey_report.html) - an interactive summary of TRPA's 2018 travel behavior survey

* [Census Data](https://rhaefer.github.io/census_101.html) - an interactive exploration of the Census APIs through the tidycensus package

***

### *2017*

* [Bird Observations](https://rhaefer.github.io/bird.html) - a visualization of my bird observations

* [Ski Tours](https://rhaefer.github.io/ski_tours.html) - a visualizaion of my backcountry ski tours

***

### *2016*

* [Transportation Funding](https://rhaefer.github.io/tableau.html) - Tableau dashboard of PSRC's 2016 Project Selection Process

***

### *2014*

* [Master's Thesis](https://digital.lib.washington.edu/researchworks/handle/1773/26844) - Assessing the relationship between city growth and electricity use over time: A comparative analysis of Chandigarh and Seattle, University of Washington

* [Public Street Light Inventory](https://drive.google.com/file/d/0B8T2r7MVXupGc3JnTDRSazZJX0U/view?usp=sharing) - Public Street and Area Lighting Inventory Phase 1: Survey Results - Municipal Solid-State Street Lighting Consortium, Prepared for U.S. Department of Energy

* [Chandigarh Urban Lab](https://drive.google.com/file/d/0B8T2r7MVXupGRXdTaFNxTDAxTE0/view?usp=sharing) - Chandigarh Urban Lab Solar-Spine, University of Washington
