---
title: "Backcountry Ski Tours"
output:
  html_document:
    theme: yeti
    highlight: tango
    code_folding: hide
---

```{r message=FALSE, warning=FALSE}
library(pacman)
pacman::p_load( gsheet, knitr,raster,leaflet,rsconnect,datasets, tidyverse,  maptools, geojsonio,
                rgdal, ggplot2, devtools, ggthemes, gtools, scales, DT, RColorBrewer, Rserve, leaflet.extras)

setwd("C:/Users/reidh/Documents/GitHub/rhaefer.github.io/ski_tours")
shapefile <- readOGR(dsn=".", layer="tours_ski",verbose = FALSE)
shapefile<-spTransform(shapefile, CRS("+proj=longlat +datum=WGS84"))
ski_points <- readOGR(dsn=".", layer="ski_points",verbose = FALSE)
ski_points<-spTransform(ski_points, CRS("+proj=longlat +datum=WGS84"))

data1<-read_csv("Ski Tours.csv")
data1<- data1[complete.cases(data1),]
data1$tour.name <- tolower(data1$`tour name`)
data1$id<- as.factor(data1$id)
shapefile@data <- left_join(shapefile@data, data1, by="id")

shapefile1<-shapefile
shapefile1$name<-gsub("South Trail to Bullion Basin Trail, Pierce County, WA, USA", "east peak circumnaviation",shapefile1$name )
shapefile1$date<-as.Date(shapefile1$date, "%m/%d/%Y")
shapefile1$date<-format(shapefile1$date, "%B %d, %Y")



#custom topographic map created with Mapbox
topo <- "https://api.mapbox.com/styles/v1/reidhaefer/cizzrfkq7007d2ss1ob7e2j43/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoicmVpZGhhZWZlciIsImEiOiJjaW80bW92cGowMW8zdjRrcWlsMzg5dGVjIn0.TxdQscN__5Nlu_jSYxZplA"
mb_attribution <- "<a href='https://www.mapbox.com/map-feedback/'>Mapbox</a> <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>"

#custom base map map created with Mapbox
base_map <- "https://api.mapbox.com/styles/v1/reidhaefer/cj04a1fmm00332sroid5qzzwb/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoicmVpZGhhZWZlciIsImEiOiJjaW80bW92cGowMW8zdjRrcWlsMzg5dGVjIn0.TxdQscN__5Nlu_jSYxZplA"
mb_attribution <- "<a href='https://www.mapbox.com/map-feedback/'>Mapbox</a> <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>"

leaflet(width=900, height=700) %>%
 # addMarkers(
   # lng = -121.8144, lat = 48.7767,
   # label = "Label w/o surrounding box",
   # labelOptions = labelOptions(noHide = T, textOnly = TRUE)) %>%
  addPopups(-119.250479, 37.939091, "recent trip", options = popupOptions(closeButton = FALSE)) %>%
  addProviderTiles(providers$OpenStreetMap.BlackAndWhite) %>%
  addTiles(urlTemplate = base_map, attribution = mb_attribution, group="Base Map") %>%
  addTiles(urlTemplate = topo, attribution = mb_attribution, group="Topographic") %>%
  addProviderTiles("Esri.WorldImagery", group="Satellite") %>%
  addPolylines(data=shapefile1, weight=4, color="red", label=~paste(name,"-",`general area`),
               popup=paste(sep="<br/>",paste("<b>Tour Name:</b> ",shapefile1$name),
                           paste("<b>Date:</b> ",shapefile1$date),
                           paste("<b>Location:</b> ",shapefile1$`general area`),
                           paste("<b>Distance:</b> ",shapefile1$`distance (mile)`, "miles"),
                           paste("<b>Elevation Gained:</b> ",shapefile1$`elevation gain (ft)`, "feet"),
                           paste("<b>Weather:</b> ",shapefile1$weather),
                           paste("<b>Avalanche Forecast:</b> ",shapefile1$`nwac avy rating`),
                           paste0("<a href=", "\"", shapefile1$photos, "\"", "target=", "\"","blank", "\"", ">","Photos" ,"</a>")),
               highlightOptions = highlightOptions(color = "#02f9dd", weight = 2, bringToFront = TRUE)) %>%
  addMiniMap(toggleDisplay = TRUE, tiles=providers$OpenStreetMap.BlackAndWhite) %>%
  addEasyButton(easyButton(icon="fa-globe", title="Zoom to Level 1", onClick=JS("function(btn, map){ map.setZoom(6); }"))) %>%
  addLegend("topright", title= "Backcountry Ski Tours", colors= "#c60905", labels= "ski tour") %>%
  addLayersControl(baseGroups = c("Topographic","Base Map",  "Satellite"), options = layersControlOptions(collapsed = FALSE)) %>%
   addCircleMarkers(data=ski_points, lng = ~MEAN_X, lat = ~MEAN_Y, label= ~UID, group ='ski_points',
                     fill=F, stroke=FALSE) %>%
  addSearchMarker( targetGroup = 'ski_points', options = searchMarkersOptions(zoom=12, openPopup = TRUE,
        hideMarkerOnCollapse = TRUE))
```


```{r message=FALSE, warning=FALSE}

data_table<-data1 %>% select(date, `general area`, tour.name, `nwac avy rating`, weather, duration, `elevation gain (ft)`, `distance (mile)`, photos )
data_table$photos <- paste0("<a href=", "\"", data_table$photos, "\"", "target=", "\"","blank", "\"", ">", data_table$tour.name, "</a>")
data_table$`distance (mile)`<- paste(data_table$`distance (mile)`, "miles")
data_table$`elevation gain (ft)`<- paste(data_table$`elevation gain (ft)`, "ft")
colnames(data_table)<-c("Date", "Area", "Tour Name", "Avalanche Danger", "Weather", "Duration", "Elevation Gain", "Distance" ,"Photos")
data_table$Date <- as.Date(data_table$Date, "%m/%d/%Y")
data_table<-data_table[order(as.Date(data_table$Date, format="%m/%d/%Y"), decreasing = TRUE),]
data_table$Date<-as.Date(data_table$Date, "%m/%d/%Y")
data_table$Date<-format(data_table$Date, "%B %d, %Y")
data_table <- data_table[complete.cases(data_table),]

DT::datatable(data_table, rownames=FALSE, escape=FALSE, options=list(pageLength = 100, dom = 'ft'))
```
